### PR TITLE
Add 5inch and 3inch PMTs as a copy of 8inch PMT

### PR DESCRIPTION
**Pull request by Tomoyo-Yoshida**
Added 3 types of PMTs (PMT5inch, PMT3inch, and PMT3inchGT).

Charge and timing response of PMT5inch is just a copy of those of PMT8inch, the same as nuPRISM/develop.
Charge response of PMT3inch is a copy of those of PMT8inch, and its transit time spread is about 4ns FWHM when charge is 1p.e.
PMT3inchGT has the same charge response as PMT3inch, while PMT3inchGT has better timing resolution of 2.5ns FWHM at 1p.e.

### CODE REVIEW

**Comment by Tomoyo-Yoshida** [comment]
Added PMT3inchR12199_02 based on Tom's modeling.

**Comment by mscott201** [comment]
Can you make sure this pull request and pull #19 are not duplicates of one another as well?

**Comment by Tomoyo-Yoshida** [comment]
I am sorry, but I do not understand what you really want to ask me. This pull request is for nuPRISM/master branch and pull request #19 is for nuPRISM/develop branch. The codes for PMT response are the exactly same to each other.

**Comment by mscott201** [comment]
Sorry - I realise my question wasn't very clear.  I really wanted to know if there was any difference between the code in the two pull requests, but it seems like there isn't.

In general we shouldn't be making pull requests directly to the master branch of the repository unless they are to fix critical bugs (such as the muon decay bug).  This guarantees that the master branch is identical to the current 'production' version of WCSim/nuPRISM for everyone that updates their repositories.

With that in mind I'd like to close this pull request without merging and merge pull request 19.  I think this means that the WCSim/nuPRISM/develop branch would include all of the PMT information you have been using for the fiTQun studies, and could then be merged into the master branch for the next release.  Is that correct?

Let me know what you think.

**Comment by Tomoyo-Yoshida** [comment]
Thank you, Mark. Now I understand.
Yes, pull request 19 has all the information I use for fiTQun studies.

**Pull request closed without merging**
