### PR TITLE
Adding parent G4 track id

### PR DESCRIPTION
**Pull request by akutsuR**
Added parent track's geant4 id to each track saved in WCRootEvent

### CODE REVIEW

**Review by nickwp — APPROVED** [review]
This looks good to me, very useful feature to have.

**Review by pdeperio — APPROVED** [review]
ok. this will be the first PR after the HK hybrid merge. so we need to start keeping track of MC productions with proper tags.

**Comment by pdeperio** [comment]
@akutsuR did you mean to close this?

my last comment implied we should tag before merging this. @nickwp are you able to do this?

**Comment by akutsuR** [comment]
@pdeperio Sorry that I mistakenly closed it as I'm going to make another PR for pile-up particle gun event generation.

**Comment by nickwp** [comment]
Can do. How should we name the current version tag before re-opening and merging this PR? As far as I know that version has not been used for any productions (or anything else, yet? @akutsuR can correct me if I'm wrong but I believe the version for his productions were from before Benjamin's merge).

**Comment by pdeperio** [comment]
@akutsuR it is good to make separate PRs for different features.

@nickwp how about `hkhybrid-v1.0.0`?

**Comment by akutsuR** [comment]
> Can do. How should we name the current version tag before re-opening and merging this PR? As far as I know that version has not been used for any productions (or anything else, yet? @akutsuR can correct me if I'm wrong but I believe the version for his productions were from before Benjamin's merge).

**Comment by akutsuR** [comment]
@nickwp Yes. this has never been used for any productions.
@pdeperio  I agree with you. I will make another PR.

**Comment by akutsuR** [comment]
Sorry for closing the PR again..... As for another PR, can I make a new branch under nuPRISM/WCSim and merge my updates and the new branch?

**Comment by nickwp** [comment]
Okay, I've tagged so will merge this PR now.

> Sorry for closing the PR again..... As for another PR, can I make a new branch under nuPRISM/WCSim and merge my updates and the new branch?

I think a new branch for the pile-up changes sounds good, then we can both merge our changes into that. And when it's ready we can have a PR into this branch?

**Comment by akutsuR** [comment]
@pdeperio @nickwp Do I need a permission to create a new branch under nuPRISM/WCSim?

**Pull request merged**
