### PR TITLE
Niball

### PR DESCRIPTION
**Pull request by pabloferm**
Preliminary implementation of Ni ball calibration source.

### CODE REVIEW

**Comment by pdeperio** [comment]
are you able to PR a new branch starting from `nuPRISM:nuPRISM/develop` base and implementing only the Ni ball changes?

@bquilain and @nickwp are working on the general merge separately...

**Comment by pabloferm** [comment]
Sure! Sorry about that.

**Comment by pdeperio** [comment]
n/p, is this what @jerenner is or should be using?

**Comment by pabloferm** [comment]
As far as I understand he is simulating the gamma spectrum of the Nickel source. This implementation is based on that from SK which is quite old, so his work should be eventually added to this in order to have more up-to-date/realistic simulation.

**Comment by pabloferm** [comment]
Hi @pdeperio, could you grant me access to the 'nuPRISM:nuPRISM/develop' repository so I can commit the branch?

**Comment by pabloferm** [comment]
I've seen your invitation but no change...

Username for 'https://github.com': pabloferm
Password for 'https://pabloferm@github.com': 
remote: Permission to nuPRISM/WCSim.git denied to pabloferm.
fatal: unable to access 'https://github.com/nuPRISM/WCSim.git/': The requested URL returned error: 403

**Comment by pdeperio** [comment]
what command are you trying to run?

you should start from your own fork of this repository, and make sure you're on `nuPRISM/develop` branch or a new branch based off it, before implementing the necessary functions. Then you PR your fork/branch to this head.

**Comment by pabloferm** [comment]
[pablofer@sukap002 WCSim]$ git branch
* niball
  nuPRISM/develop
[pablofer@sukap002 WCSim]$ git push -u origin niball

**Comment by pdeperio** [comment]
ya so make your own fork first as in [above msg](https://github.com/nuPRISM/WCSim/pull/58#issuecomment-824997023)

**Comment by pabloferm** [comment]
OK, that's done. Closing the PR.

**Pull request closed without merging**
