### PR TITLE
PMT saturation

### PR DESCRIPTION
**Pull request by EuanRichard**
Implementation of PMT saturation.

Just a Gaussian method, with default parameters taken from SKDetsim (but implemented in a less discontinuous way).

Turned off by default - includes appropriate macro commands for usage (see novis.mac).

saturation

### CODE REVIEW

**Comment by mscott201** [comment]
Hi Euan,

Sorry, what is this request for?  I don't see anything wrong with the commits, but I didn't realise we needed this saturation correction for nuPRISM.  Is this specifically a nuPRISM issue, or is it a wider WCSim problem?

**Comment by EuanRichard** [comment]
Hi Mark,

It's just something Mark (Hartz) asked me to add. The end goal was to see if there was any effects on the physics, but there was some funny behavior with the previous fitqun version I was using, so didn't get any conclusive results.

It's also something they are planning on adding in WCSim, although I didn't ask Chris (Walter) yet if there was any particular way they wanted it implemented.

**Comment by wilking** [comment]
In order to test this, we have to implement a charge threshold and regenerate the charge (and time) PDFs for fiTQun. If this code is properly turned off by default, then it can be committed, and we can try tuning to it in the future.

**Comment by mscott201** [comment]
OK - since this is something that is going to be added to WCSim eventually you should have created a new branch from the 'develop' branch in the nuPRISM repository (git checkout -b myFeature develop), and made your changes there.

Then, you can issue a pull request for the code back to the WCSim organisation and to the nuPRISM organisation.  Once the WCSim organisation is happy with the code changes then we can both accept the pull request.

If the WCSim organisation stuff is too slow, we at nuPRISM can always accept the pull request earlier and start studying the saturation, then just update our code in the future.

**Pull request closed without merging**
